app:
  build: app
  links:
   - influxdb
  ports:
   - "8080:8080"
#  volumes:
#   - ./app:/usr/src/app
influxdb:
  environment:
    - PRE_CREATE_DB=todomvc
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
grafana:
  image: grafana/grafana
  links:
    - influxdb
  ports:
    - "3000:3000"
